name: "action-sonarqube-dotnet"
description: "SonarScanner for .NET"
author: "calxus"

inputs:
  sonarProjectKey:
    description: "The key of the SonarQube project"
    required: true
  sonarHostname:
    description: "The SonarQube server URL. For SonarCloud, skip this setting."
    default: "https://sonarcloud.io"
    required: false
   nugetSource:
    description: "A custom nuget source"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: 'check-square'
  color: 'blue'
